# Generated by Django 4.2.6 on 2023-10-26 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "attributes",
            "0002_activitystatus_reviewstatus_alter_course_options_and_more",
        ),
        ("employers", "0001_initial"),
        ("students", "0002_education_job_portfoliolink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный id",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(verbose_name="Опубликована"),
                ),
                (
                    "publish_date",
                    models.DateField(verbose_name="Дата публикации"),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Должность"),
                ),
                ("occupation", models.CharField(max_length=20)),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                ("min_salary", models.PositiveIntegerField()),
                ("max_salary", models.PositiveIntegerField()),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attributes.workformat",
                        verbose_name="Тип",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attributes.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employers.employer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "default_related_name": "vacancies",
            },
        ),
        migrations.CreateModel(
            name="Respond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.applicant",
                        verbose_name="Соискатель",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attributes.reviewstatus",
                        verbose_name="Статус рассмотрения отклика",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
                "default_related_name": "responds",
            },
        ),
        migrations.AddConstraint(
            model_name="respond",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "applicant"),
                name="Уникальная пара Вакансия - Соискатель",
            ),
        ),
    ]
