# Generated by Django 4.2.6 on 2023-10-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0003_occupation"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="occupation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="attributes.occupation",
                verbose_name="Занятость",
            ),
        ),
    ]
