# Generated by Django 4.2.6 on 2023-10-27 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_alter_vacancy_occupation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="publish_date",
        ),
    ]
