# Generated by Django 4.2.6 on 2023-10-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0003_occupation"),
        ("vacancies", "0004_alter_vacancy_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="respond",
            options={
                "default_related_name": "responds",
                "ordering": ("-created_at",),
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
            },
        ),
        migrations.AlterField(
            model_name="respond",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="attributes.reviewstatus",
                verbose_name="Статус рассмотрения отклика",
            ),
        ),
    ]
