# Generated by Django 4.2.6 on 2023-10-24 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attributes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный id",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="images/students/default.jpg",
                        upload_to="images/students/%Y/%m/%d/",
                        verbose_name="Фото профиля",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Фамилия"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, verbose_name="Дата рождения"),
                ),
                (
                    "can_relocate",
                    models.BooleanField(verbose_name="Релокация"),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на портфолио"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "в активном поиске"),
                            ("inactive", "не ищу работу"),
                            ("hired", "устроен на работу"),
                        ],
                        max_length=20,
                        verbose_name="Статус активности",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[("middle", "среднее"), ("high", "высшее")],
                        max_length=20,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant",
                        to="attributes.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicant",
                        to="attributes.contact",
                        verbose_name="Контакт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соискатель",
                "verbose_name_plural": "Соискатели",
            },
        ),
        migrations.CreateModel(
            name="ApplicantDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала работы"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания работы",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        verbose_name="В настоящее время работает",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_directions",
                        to="students.applicant",
                        verbose_name="Соискатель",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_directions",
                        to="attributes.direction",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт работы",
                "verbose_name_plural": "Опыт работы",
            },
        ),
        migrations.CreateModel(
            name="ApplicantCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(verbose_name="Дата окончания курса"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_courses",
                        to="students.applicant",
                        verbose_name="Соискатель",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_courses",
                        to="attributes.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пройденные курсы",
                "verbose_name_plural": "Пройденные курсы",
            },
        ),
        migrations.AddField(
            model_name="applicant",
            name="courses",
            field=models.ManyToManyField(
                related_name="applicants",
                through="students.ApplicantCourse",
                to="attributes.course",
                verbose_name="Пройденные курсы",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="directions",
            field=models.ManyToManyField(
                related_name="applicants",
                through="students.ApplicantDirection",
                to="attributes.direction",
                verbose_name="Должности",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="stack",
            field=models.ManyToManyField(
                related_name="applicant",
                to="attributes.stack",
                verbose_name="Стек",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="work_format",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applicant",
                to="attributes.workformat",
                verbose_name="Формат работы",
            ),
        ),
    ]
