# Generated by Django 4.2.6 on 2023-10-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "attributes",
            "0002_activitystatus_alter_course_options_remove_city_slug_and_more",
        ),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название"),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала работы"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания работы",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        verbose_name="В настоящее время работает",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работа",
            },
        ),
        migrations.CreateModel(
            name="PortfolioLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "link",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на портфолио"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на портфолио",
                "verbose_name_plural": "Ссылка на портфолио",
            },
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="directions",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="education_level",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="portfolio_link",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applicant",
                to="attributes.activitystatus",
                verbose_name="Статус",
            ),
        ),
        migrations.DeleteModel(
            name="ApplicantDirection",
        ),
        migrations.AddField(
            model_name="portfoliolink",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_links",
                to="students.applicant",
                verbose_name="Ссылка на портфолио",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="students.applicant",
                verbose_name="Соискатель",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="students.applicant",
                verbose_name="Образование",
            ),
        ),
    ]
