# Generated by Django 4.2.6 on 2023-10-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0003_occupation"),
        ("students", "0002_education_job_portfoliolink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="can_relocate",
        ),
        migrations.AddField(
            model_name="applicant",
            name="occupation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applicant",
                to="attributes.occupation",
                verbose_name="Тип занятости",
            ),
        ),
    ]
