# Generated by Django 4.2.6 on 2023-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0005_employeesnumber_alter_course_options_and_more"),
        ("students", "0004_remove_applicant_occupation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="occupation",
            field=models.ManyToManyField(
                related_name="applicants",
                to="attributes.occupation",
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="work_format",
            field=models.ManyToManyField(
                related_name="applicants",
                to="attributes.workformat",
                verbose_name="Формат работы",
            ),
        ),
    ]
