# Generated by Django 4.2.6 on 2023-10-26 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "attributes",
            "0002_activitystatus_reviewstatus_alter_course_options_and_more",
        ),
        ("students", "0002_education_job_portfoliolink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название компании"
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        max_length=1000, verbose_name="О компании"
                    ),
                ),
                ("website", models.URLField(verbose_name="Ссылка на сайт")),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный id",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employers",
                        to="employers.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attributes.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работодатель",
                "verbose_name_plural": "Работодатели",
            },
        ),
        migrations.CreateModel(
            name="SelectedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        max_length=255, verbose_name="Комментарии"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_by",
                        to="students.applicant",
                        verbose_name="Соискатель",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_resume",
                        to="employers.employer",
                        verbose_name="Работодатель",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attributes.reviewstatus",
                        verbose_name="Статус кандидата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отобранный соискатель",
                "verbose_name_plural": "Отобранные соискатели",
            },
        ),
        migrations.AddConstraint(
            model_name="selectedresume",
            constraint=models.UniqueConstraint(
                fields=("employer", "applicant"),
                name="Уникальная пара Работодатель - Соискатель",
            ),
        ),
    ]
