# Generated by Django 4.2.6 on 2023-10-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0004_alter_direction_options"),
        ("employers", "0003_alter_selectedresume_employer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectedresume",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="attributes.reviewstatus",
                verbose_name="Статус кандидата",
            ),
        ),
    ]
