# Generated by Django 4.2.6 on 2023-10-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0004_alter_selectedresume_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectedresume",
            name="comments",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Комментарии"
            ),
        ),
    ]
