# Generated by Django 4.2.6 on 2023-10-29 19:05

import apps.employers.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0005_employeesnumber_alter_course_options_and_more"),
        ("employers", "0005_alter_selectedresume_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="employees_qty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="attributes.employeesnumber",
                verbose_name="Численность сотрудников",
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="foundation_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[apps.employers.validators.validate_year],
                verbose_name="Год основания",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="diplomas/%Y-%m-%d",
                        verbose_name="Scanned document",
                    ),
                ),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="employers.employer",
                        verbose_name="Коммпания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
