# Generated by Django 4.2.6 on 2023-10-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "employers",
            "0006_employer_employees_qty_employer_foundation_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="employer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="employers.employer",
                verbose_name="Компания",
            ),
        ),
    ]
