# Generated by Django 4.2.6 on 2023-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0007_alter_document_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/%Y-%m-%d",
                verbose_name="Документ",
            ),
        ),
    ]
