# Generated by Django 4.2.6 on 2023-10-29 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0008_employer_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employer",
            old_name="employees_qty",
            new_name="employees_number",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
