# Generated by Django 4.2.6 on 2023-10-26 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
            ],
            options={
                "verbose_name": "Статус активности",
                "verbose_name_plural": "Статусы активности",
            },
        ),
        migrations.CreateModel(
            name="ReviewStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
            ],
            options={
                "verbose_name": "Статус рассмотрения",
                "verbose_name_plural": "Статусы рассмотрения",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "verbose_name": "Связь курса и направления",
                "verbose_name_plural": "Связи курсов и направлений",
            },
        ),
        migrations.RemoveField(
            model_name="city",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="stack",
            name="slug",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="direction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_directions",
                to="attributes.direction",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workformat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workformat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="stack",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="workformat",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
