# Generated by Django 4.2.6 on 2023-10-28 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attributes", "0003_occupation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
    ]
